version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:5173"
    container_name: task-manager-frontend
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    networks:
      - task-manager-network

networks:
  task-manager-network:
    driver: bridge

